CREATE DATABASE 03_supermarket;

USE 03_supermarket;

CREATE TABLE users (
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100),
 email VARCHAR(100),
 password VARCHAR(100),
 phone VARCHAR(20),
 image VARCHAR(255),
 location VARCHAR(255),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);